# Generated by Django 6.0.3 on 2026-03-17 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_refeicao'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroConsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_e_hora', models.DateTimeField(auto_now_add=True)),
                ('repeticao', models.BooleanField(default=False)),
                ('convidado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.convidado')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.evento')),
                ('refeicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.refeicao')),
            ],
        ),
    ]
